title = 'SpaceTelescope Notebooks'
description = 'A space for Astronomy Notebooks'
keywords = ['stsci', 'spacetelescope', 'jupyter', 'notebooks', 'astronomy']
author = 'spacetelescope'
maintainer = 'Michael Gough'
default_locale = 'en'
website_base_url = 'https://spacetelescope.github.io/dat_pyinthesky'
index_title = 'Notebook Index'
locale = 'en'
notebook_title = 'JDAT Notebook'
notebook_keywords = ['stsci', 'spacetelescope', 'jupyter', 'notebooks', 'astronomy']
notebook_description = 'A space for Astronomy Notebooks'
