# This file performs testing using tox and tox.ini to define and configure the test environments.
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Code style checks
            os: ubuntu-20.04
            python: 3.x
            toxenv: codestyle

          - name: PEP 517
            os: ubuntu-20.04
            python: 3.x
            toxenv: pep517

          - name: Security audit
            os: ubuntu-20.04
            python: 3.x
            toxenv: securityaudit

          # Python 3.6
          - name: Linux - Python 3.6
            os: ubuntu-20.04
            python: 3.6
            toxenv: py36-test

          - name: OS X - Python 3.6
            os: macos-10.15
            python: 3.6
            toxenv: py36-test

          - name: Windows - Python 3.6
            os: windows-2019
            python: 3.6
            toxenv: py36-test

          # Python 3.7
          - name: Linux - Python 3.7
            os: ubuntu-20.04
            python: 3.7
            toxenv: py37-test

          - name: OS X - Python 3.7
            os: macos-10.15
            python: 3.7
            toxenv: py37-test

          - name: Windows - Python 3.7
            os: windows-2019
            python: 3.7
            toxenv: py37-test

          # Python 3.8
          - name: Linux - Python 3.8
            os: ubuntu-20.04
            python: 3.8
            toxenv: py38-test

          - name: OS X - Python 3.8
            os: macos-10.15
            python: 3.8
            toxenv: py38-test

          - name: Windows - Python 3.8
            os: windows-2019
            python: 3.8
            toxenv: py38-test

          # Python 3.9
          - name: Linux - Python 3.9
            os: ubuntu-20.04
            python: 3.9
            toxenv: py39-test

          - name: OS X - Python 3.9
            os: macos-10.15
            python: 3.9
            toxenv: py39-test

          - name: Windows - Python 3.9
            os: windows-2019
            python: 3.9
            toxenv: py39-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up python ${{ matrix.python }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}

    # Activate your repo on codecov.io first.
    - name: Upload coverage to codecov
      if: "contains(matrix.toxenv, '-cov')"
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
